### ISSUE TITLE
Java version split breaks compatibility

### ISSUE THREAD

**Issue by merlijn-sebrechts** [juju-solutions/jujubigdata#22]
Commit: https://github.com/juju-solutions/jujubigdata/commit/a291a7001b0685efc4de2d88379378712ba8b4d1

```
+        java_major, java_release = java_version.split("_") 
         unitdata.kv().set('java.home', java_home)
-        unitdata.kv().set('java.version', java_version)
+        unitdata.kv().set('java.version', java_major)
```

This causes add-unit to fail if the existing cluster has the previous version of jujubigdata and the new unit has the next one. I think a change that breaks backwards compatibility like this should be in a minor version. It is very frustrating that there is no safeguard for problems like this since jujubigdata gets downloaded during installation.

Does the layered approach fix problems like this?

**Comment by andrewdmcleod** [comment]
Hi Merlijn,

This should in fact have been a major version bump - however, the old
jujubigdata library was broken - we were specifying the version to install
(e.g. 1.7.0) but the spec match was using the full version + release
string, e.g.:

...u'{"java": "1.7.0_91",...

The reason for the split was that we found that when a new release of the
same version was pushed into the repo, we weren't able to add units due to
a spec mismatch. (e.g. "1.7.0_91" vs "1.7.0_82") - and we were not locking
on a specific release - we decided against locking the release due to the
fact that often these are security fixes/patches, and otherwise it seems
the only way to provide backward compatibility to the old jujubigdata
library would have been to fake the release number in the spec for new
units, is clearly not best practice.

What I should have done better was to make this bug and subsequent change
more visible to the community, so I apologise for that oversight.

As to whether or not the layered approach will resolve this, the reason we
have jujubigdata installed at deploy time is because we had a lot of churn
on that library at first and it was significantly more difficult to update
all the charms if it was bundled.  With layers, though, we should be able
to issue an easily scriptable set of `charm build` commands, with at most
editing a single layer.  That, plus the library having calmed down quite a
bit, leads me to think that we should start bundling it directly in the
layered charms.  Thus, we'd move to an approach of having all of the charm
deps bundled via the wheelhouse and only pull in the payload at deploy time.

Andrew

On Thu, Dec 3, 2015 at 11:40 AM, Merlijn Sebrechts <notifications@github.com

**Comment by merlijn-sebrechts** [comment]
Hi Andrew

Thanks for the answer. I totally agree on the patch and the reason to break compatibility. As you said, this should've been a major version update.

What do you propose as a fix (if any)? Bump a major version, or just leave it at that? I suppose other people could run into this problem if they have a running cluster..

Regards
Merlijn

**Comment by johnsca** [comment]
Closing this, as I believe it was resolved.  Reopen if necessary.
